// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<string>;

export function GetGateways(arg1:string):Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function SignOut():Promise<string>;
