// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/gateway/v1/gateway.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Gateway auth token
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionIPRequest) Reset() {
	*x = GetSessionIPRequest{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionIPRequest) ProtoMessage() {}

func (x *GetSessionIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionIPRequest.ProtoReflect.Descriptor instead.
func (*GetSessionIPRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionIPRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *GetSessionIPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionIPRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetSessionIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionIPResponse) Reset() {
	*x = GetSessionIPResponse{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionIPResponse) ProtoMessage() {}

func (x *GetSessionIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionIPResponse.ProtoReflect.Descriptor instead.
func (*GetSessionIPResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionIPResponse) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type SyncSessionsRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	AuthToken     string                         `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Sessions      []*SyncSessionsRequest_Session `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSessionsRequest) Reset() {
	*x = SyncSessionsRequest{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSessionsRequest) ProtoMessage() {}

func (x *SyncSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSessionsRequest.ProtoReflect.Descriptor instead.
func (*SyncSessionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SyncSessionsRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *SyncSessionsRequest) GetSessions() []*SyncSessionsRequest_Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SyncSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSessionsResponse) Reset() {
	*x = SyncSessionsResponse{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSessionsResponse) ProtoMessage() {}

func (x *SyncSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSessionsResponse.ProtoReflect.Descriptor instead.
func (*SyncSessionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SyncSessionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DeviceHash    string                 `protobuf:"bytes,3,opt,name=device_hash,json=deviceHash,proto3" json:"device_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetDeviceHash() string {
	if x != nil {
		return x.DeviceHash
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,3,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"` // Current config hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type HeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ConfigUpdateAvailable bool                   `protobuf:"varint,2,opt,name=config_update_available,json=configUpdateAvailable,proto3" json:"config_update_available,omitempty"` // Signal if update is needed
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetConfigUpdateAvailable() bool {
	if x != nil {
		return x.ConfigUpdateAvailable
	}
	return false
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GetConfigRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type GetConfigResponse struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	VpnCidr          string                      `protobuf:"bytes,1,opt,name=vpn_cidr,json=vpnCidr,proto3" json:"vpn_cidr,omitempty"`
	PublicKeyPem     string                      `protobuf:"bytes,2,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"`
	ConfigHash       string                      `protobuf:"bytes,3,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Policies         []*GetConfigResponse_Policy `protobuf:"bytes,4,rep,name=policies,proto3" json:"policies,omitempty"`
	MaxBandwidthMbps int64                       `protobuf:"varint,5,opt,name=max_bandwidth_mbps,json=maxBandwidthMbps,proto3" json:"max_bandwidth_mbps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetConfigResponse) GetVpnCidr() string {
	if x != nil {
		return x.VpnCidr
	}
	return ""
}

func (x *GetConfigResponse) GetPublicKeyPem() string {
	if x != nil {
		return x.PublicKeyPem
	}
	return ""
}

func (x *GetConfigResponse) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *GetConfigResponse) GetPolicies() []*GetConfigResponse_Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *GetConfigResponse) GetMaxBandwidthMbps() int64 {
	if x != nil {
		return x.MaxBandwidthMbps
	}
	return 0
}

type SyncSessionsRequest_Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ConnectedAt   int64                  `protobuf:"varint,4,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSessionsRequest_Session) Reset() {
	*x = SyncSessionsRequest_Session{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSessionsRequest_Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSessionsRequest_Session) ProtoMessage() {}

func (x *SyncSessionsRequest_Session) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSessionsRequest_Session.ProtoReflect.Descriptor instead.
func (*SyncSessionsRequest_Session) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SyncSessionsRequest_Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncSessionsRequest_Session) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SyncSessionsRequest_Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SyncSessionsRequest_Session) GetConnectedAt() int64 {
	if x != nil {
		return x.ConnectedAt
	}
	return 0
}

type GetConfigResponse_Policy struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action                string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	SourceTagType         string                 `protobuf:"bytes,3,opt,name=source_tag_type,json=sourceTagType,proto3" json:"source_tag_type,omitempty"`
	SourceMatchValue      string                 `protobuf:"bytes,4,opt,name=source_match_value,json=sourceMatchValue,proto3" json:"source_match_value,omitempty"`
	DestinationTagType    string                 `protobuf:"bytes,5,opt,name=destination_tag_type,json=destinationTagType,proto3" json:"destination_tag_type,omitempty"`
	DestinationMatchValue string                 `protobuf:"bytes,6,opt,name=destination_match_value,json=destinationMatchValue,proto3" json:"destination_match_value,omitempty"`
	Priority              int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetConfigResponse_Policy) Reset() {
	*x = GetConfigResponse_Policy{}
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse_Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse_Policy) ProtoMessage() {}

func (x *GetConfigResponse_Policy) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse_Policy.ProtoReflect.Descriptor instead.
func (*GetConfigResponse_Policy) Descriptor() ([]byte, []int) {
	return file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetConfigResponse_Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetSourceTagType() string {
	if x != nil {
		return x.SourceTagType
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetSourceMatchValue() string {
	if x != nil {
		return x.SourceMatchValue
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetDestinationTagType() string {
	if x != nil {
		return x.DestinationTagType
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetDestinationMatchValue() string {
	if x != nil {
		return x.DestinationMatchValue
	}
	return ""
}

func (x *GetConfigResponse_Policy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_internal_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_internal_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"'internal/proto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"l\n" +
	"\x13GetSessionIPRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\"5\n" +
	"\x14GetSessionIPResponse\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\"\xff\x01\n" +
	"\x13SyncSessionsRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12C\n" +
	"\bsessions\x18\x02 \x03(\v2'.gateway.v1.SyncSessionsRequest.SessionR\bsessions\x1a\x83\x01\n" +
	"\aSession\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12!\n" +
	"\fconnected_at\x18\x04 \x01(\x03R\vconnectedAt\"0\n" +
	"\x14SyncSessionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1f\n" +
	"\vdevice_hash\x18\x03 \x01(\tR\n" +
	"deviceHash\"1\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"j\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vconfig_hash\x18\x03 \x01(\tR\n" +
	"configHash\"e\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\x17config_update_available\x18\x02 \x01(\bR\x15configUpdateAvailable\"1\n" +
	"\x10GetConfigRequest\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"\xf8\x03\n" +
	"\x11GetConfigResponse\x12\x19\n" +
	"\bvpn_cidr\x18\x01 \x01(\tR\avpnCidr\x12$\n" +
	"\x0epublic_key_pem\x18\x02 \x01(\tR\fpublicKeyPem\x12\x1f\n" +
	"\vconfig_hash\x18\x03 \x01(\tR\n" +
	"configHash\x12@\n" +
	"\bpolicies\x18\x04 \x03(\v2$.gateway.v1.GetConfigResponse.PolicyR\bpolicies\x12,\n" +
	"\x12max_bandwidth_mbps\x18\x05 \x01(\x03R\x10maxBandwidthMbps\x1a\x90\x02\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12&\n" +
	"\x0fsource_tag_type\x18\x03 \x01(\tR\rsourceTagType\x12,\n" +
	"\x12source_match_value\x18\x04 \x01(\tR\x10sourceMatchValue\x120\n" +
	"\x14destination_tag_type\x18\x05 \x01(\tR\x12destinationTagType\x126\n" +
	"\x17destination_match_value\x18\x06 \x01(\tR\x15destinationMatchValue\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority2\x91\x03\n" +
	"\x0eGatewayService\x12E\n" +
	"\bRegister\x12\x1b.gateway.v1.RegisterRequest\x1a\x1c.gateway.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.gateway.v1.HeartbeatRequest\x1a\x1d.gateway.v1.HeartbeatResponse\x12H\n" +
	"\tGetConfig\x12\x1c.gateway.v1.GetConfigRequest\x1a\x1d.gateway.v1.GetConfigResponse\x12Q\n" +
	"\fGetSessionIP\x12\x1f.gateway.v1.GetSessionIPRequest\x1a .gateway.v1.GetSessionIPResponse\x12Q\n" +
	"\fSyncSessions\x12\x1f.gateway.v1.SyncSessionsRequest\x1a .gateway.v1.SyncSessionsResponseB*Z(tridorian-ztna/internal/proto/gateway/v1b\x06proto3"

var (
	file_internal_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_internal_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_internal_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_internal_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_internal_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_gateway_v1_gateway_proto_rawDesc), len(file_internal_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_internal_proto_gateway_v1_gateway_proto_rawDescData
}

var file_internal_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*GetSessionIPRequest)(nil),         // 0: gateway.v1.GetSessionIPRequest
	(*GetSessionIPResponse)(nil),        // 1: gateway.v1.GetSessionIPResponse
	(*SyncSessionsRequest)(nil),         // 2: gateway.v1.SyncSessionsRequest
	(*SyncSessionsResponse)(nil),        // 3: gateway.v1.SyncSessionsResponse
	(*RegisterRequest)(nil),             // 4: gateway.v1.RegisterRequest
	(*RegisterResponse)(nil),            // 5: gateway.v1.RegisterResponse
	(*HeartbeatRequest)(nil),            // 6: gateway.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 7: gateway.v1.HeartbeatResponse
	(*GetConfigRequest)(nil),            // 8: gateway.v1.GetConfigRequest
	(*GetConfigResponse)(nil),           // 9: gateway.v1.GetConfigResponse
	(*SyncSessionsRequest_Session)(nil), // 10: gateway.v1.SyncSessionsRequest.Session
	(*GetConfigResponse_Policy)(nil),    // 11: gateway.v1.GetConfigResponse.Policy
}
var file_internal_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	10, // 0: gateway.v1.SyncSessionsRequest.sessions:type_name -> gateway.v1.SyncSessionsRequest.Session
	11, // 1: gateway.v1.GetConfigResponse.policies:type_name -> gateway.v1.GetConfigResponse.Policy
	4,  // 2: gateway.v1.GatewayService.Register:input_type -> gateway.v1.RegisterRequest
	6,  // 3: gateway.v1.GatewayService.Heartbeat:input_type -> gateway.v1.HeartbeatRequest
	8,  // 4: gateway.v1.GatewayService.GetConfig:input_type -> gateway.v1.GetConfigRequest
	0,  // 5: gateway.v1.GatewayService.GetSessionIP:input_type -> gateway.v1.GetSessionIPRequest
	2,  // 6: gateway.v1.GatewayService.SyncSessions:input_type -> gateway.v1.SyncSessionsRequest
	5,  // 7: gateway.v1.GatewayService.Register:output_type -> gateway.v1.RegisterResponse
	7,  // 8: gateway.v1.GatewayService.Heartbeat:output_type -> gateway.v1.HeartbeatResponse
	9,  // 9: gateway.v1.GatewayService.GetConfig:output_type -> gateway.v1.GetConfigResponse
	1,  // 10: gateway.v1.GatewayService.GetSessionIP:output_type -> gateway.v1.GetSessionIPResponse
	3,  // 11: gateway.v1.GatewayService.SyncSessions:output_type -> gateway.v1.SyncSessionsResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_gateway_v1_gateway_proto_init() }
func file_internal_proto_gateway_v1_gateway_proto_init() {
	if File_internal_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_gateway_v1_gateway_proto_rawDesc), len(file_internal_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_internal_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_internal_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_internal_proto_gateway_v1_gateway_proto = out.File
	file_internal_proto_gateway_v1_gateway_proto_goTypes = nil
	file_internal_proto_gateway_v1_gateway_proto_depIdxs = nil
}
