// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectVPN(arg1, arg2) {
  return window['go']['main']['App']['ConnectVPN'](arg1, arg2);
}

export function DisconnectVPN() {
  return window['go']['main']['App']['DisconnectVPN']();
}

export function StartLoginProcess() {
  return window['go']['main']['App']['StartLoginProcess']();
}
