// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectVPN(arg1:string,arg2:string):Promise<string>;

export function DisconnectVPN():Promise<void>;

export function StartLoginProcess():Promise<string>;
