FROM mcr.microsoft.com/devcontainers/go:2-1.25-trixie

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    wget \
    curl \
    debianutils \
    ca-certificates