package main

import (
	"log"
	"net"
	"tridorian-ztna/internal/grpc/gateway"
	"tridorian-ztna/internal/infrastructure"
	pb "tridorian-ztna/internal/proto/gateway/v1"
	"tridorian-ztna/internal/services"
	"tridorian-ztna/pkg/utils"

	"github.com/joho/godotenv"
	"google.golang.org/grpc"
)

func main() {
	appEnv := utils.GetEnv("APP_ENV", "development")
	if appEnv == "development" {
		godotenv.Load()
	}

	log.Println("🔌 Starting Gateway gRPC Server...")

	// Database
	db := infrastructure.SetupDatabase()

	// Cache
	valkey := infrastructure.SetCache()

	// Public Key for Gateway Authentication
	// Load from environment variable (generated by ./scripts/generate-keys.sh)
	pubPEM := utils.GetEnv("ZTNA_PUBLIC_KEY", "")
	if pubPEM == "" {
		log.Fatal("❌ ZTNA_PUBLIC_KEY environment variable is required. Run: ./scripts/generate-keys.sh")
	}

	log.Printf("🔑 Public Key (PEM):\n%s", pubPEM)

	// Services
	nodeService := services.NewNodeService(db, valkey)
	policyService := services.NewPolicyService(db, valkey)

	// Start gRPC Server
	grpcPort := utils.GetEnv("GRPC_PORT", "5443")
	lis, err := net.Listen("tcp", ":"+grpcPort)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	grpcServer := grpc.NewServer()
	gatewayServer := gateway.NewServer(nodeService, policyService, pubPEM)
	pb.RegisterGatewayServiceServer(grpcServer, gatewayServer)

	log.Printf("🔌 gRPC Gateway Server listening on :%s", grpcPort)

	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("❌ gRPC Server failed: %v", err)
	}
}
